"""add company_slug to stories

Revision ID: 097094fba19a
Revises: 7c122494e1b8
Create Date: 2026-07-05 11:24:32.809408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097094fba19a'
down_revision: Union[str, Sequence[str], None] = '7c122494e1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('company_slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_stories_company_slug'), 'stories', ['company_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_company_slug'), table_name='stories')
    op.drop_column('stories', 'company_slug')
    # ### end Alembic commands ###
