"""add companies, image_categories, images tables and image_id on stories

Revision ID: 28cd62644899
Revises: e3dc62f91e1c
Create Date: 2026-07-18 14:46:24.364995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28cd62644899'
down_revision: Union[str, Sequence[str], None] = 'e3dc62f91e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('theme_bg', sa.String(), nullable=True),
    sa.Column('theme_text', sa.String(), nullable=True),
    sa.Column('tracked', sa.Boolean(), nullable=True),
    sa.Column('exclusive', sa.Boolean(), nullable=True),
    sa.Column('page_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_group_id'), 'companies', ['group_id'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('image_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_categories_id'), 'image_categories', ['id'], unique=False)
    op.create_index(op.f('ix_image_categories_key'), 'image_categories', ['key'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('image_category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['image_category_id'], ['image_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_company_id'), 'images', ['company_id'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_image_category_id'), 'images', ['image_category_id'], unique=False)
    op.add_column('stories', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stories', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.drop_column('stories', 'image_id')
    op.drop_index(op.f('ix_images_image_category_id'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_company_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_image_categories_key'), table_name='image_categories')
    op.drop_index(op.f('ix_image_categories_id'), table_name='image_categories')
    op.drop_table('image_categories')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_group_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
