"""add scrape_runs, job_flags, pipeline_run_id

Revision ID: 386295b4ca13
Revises: 590e539522e5
Create Date: 2026-07-16 11:36:20.414004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386295b4ca13'
down_revision: Union[str, Sequence[str], None] = '590e539522e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('companies_scraped', sa.Integer(), nullable=True),
    sa.Column('sources_failed', sa.String(), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('jobs_created', sa.Integer(), nullable=True),
    sa.Column('jobs_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_runs_id'), 'scrape_runs', ['id'], unique=False)
    op.create_index(op.f('ix_scrape_runs_pipeline_name'), 'scrape_runs', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_scrape_runs_status'), 'scrape_runs', ['status'], unique=False)
    op.create_table('job_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_flags_created_at'), 'job_flags', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_flags_id'), 'job_flags', ['id'], unique=False)
    op.create_index(op.f('ix_job_flags_job_id'), 'job_flags', ['job_id'], unique=False)
    op.add_column('jobs', sa.Column('pipeline_run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_jobs_pipeline_run_id'), 'jobs', ['pipeline_run_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'scrape_runs', ['pipeline_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_pipeline_run_id'), table_name='jobs')
    op.drop_column('jobs', 'pipeline_run_id')
    op.drop_index(op.f('ix_job_flags_job_id'), table_name='job_flags')
    op.drop_index(op.f('ix_job_flags_id'), table_name='job_flags')
    op.drop_index(op.f('ix_job_flags_created_at'), table_name='job_flags')
    op.drop_table('job_flags')
    op.drop_index(op.f('ix_scrape_runs_status'), table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_pipeline_name'), table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_id'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
