"""add is_active to digests, stories, companies, image_categories, images; add index to stories.image_id

Revision ID: 85be0c56097b
Revises: 28cd62644899
Create Date: 2026-07-20 02:39:21.017481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85be0c56097b'
down_revision: Union[str, Sequence[str], None] = '28cd62644899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('image_categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('images', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('stories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_stories_image_id'), 'stories', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_image_id'), table_name='stories')
    op.drop_column('stories', 'is_active')
    op.drop_column('images', 'is_active')
    op.drop_column('image_categories', 'is_active')
    op.drop_column('digests', 'is_active')
    # ### end Alembic commands ###
