"""add internal_source to stories

Revision ID: 9f085244fefe
Revises: 097094fba19a
Create Date: 2026-07-06 19:23:32.083955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f085244fefe'
down_revision: Union[str, Sequence[str], None] = '097094fba19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('internal_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'internal_source')
    # ### end Alembic commands ###
