"""add companies_with_active_jobs to scrape_runs

Revision ID: a90c537ea19d
Revises: 386295b4ca13
Create Date: 2026-07-17 09:58:35.856205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90c537ea19d'
down_revision: Union[str, Sequence[str], None] = '386295b4ca13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('companies_with_active_jobs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'companies_with_active_jobs')
    # ### end Alembic commands ###
