"""make images.url nullable, add source_url column, add is_active to ImageCreate

Revision ID: c007ef913349
Revises: ef66d82cc878
Create Date: 2026-07-24 13:05:33.418452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c007ef913349'
down_revision: Union[str, Sequence[str], None] = 'ef66d82cc878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'source_url')
    # ### end Alembic commands ###
