"""add api_keys, news_runs, fallback_log tables, add pipeline_run_id to digests

Revision ID: ef66d82cc878
Revises: 95517fb083bd
Create Date: 2026-07-21 02:10:36.160055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef66d82cc878'
down_revision: Union[str, Sequence[str], None] = '95517fb083bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_name'), 'api_keys', ['name'], unique=True)
    op.create_index(op.f('ix_api_keys_scope'), 'api_keys', ['scope'], unique=False)
    op.create_table('news_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sources_attempted', sa.Integer(), nullable=True),
    sa.Column('sources_failed', sa.String(), nullable=True),
    sa.Column('stories_found', sa.Integer(), nullable=True),
    sa.Column('stories_created', sa.Integer(), nullable=True),
    sa.Column('stories_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_runs_id'), 'news_runs', ['id'], unique=False)
    op.create_index(op.f('ix_news_runs_pipeline_name'), 'news_runs', ['pipeline_name'], unique=False)
    op.create_index(op.f('ix_news_runs_status'), 'news_runs', ['status'], unique=False)
    op.create_table('fallback_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fallback_type', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('news_run_id', sa.Integer(), nullable=True),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['news_run_id'], ['news_runs.id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fallback_log_created_at'), 'fallback_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_fallback_log_entity_type'), 'fallback_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_fallback_log_fallback_type'), 'fallback_log', ['fallback_type'], unique=False)
    op.create_index(op.f('ix_fallback_log_id'), 'fallback_log', ['id'], unique=False)
    op.create_index(op.f('ix_fallback_log_news_run_id'), 'fallback_log', ['news_run_id'], unique=False)
    op.create_index(op.f('ix_fallback_log_scrape_run_id'), 'fallback_log', ['scrape_run_id'], unique=False)
    op.add_column('digests', sa.Column('pipeline_run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_digests_pipeline_run_id'), 'digests', ['pipeline_run_id'], unique=False)
    op.create_foreign_key(None, 'digests', 'news_runs', ['pipeline_run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'digests', type_='foreignkey')
    op.drop_index(op.f('ix_digests_pipeline_run_id'), table_name='digests')
    op.drop_column('digests', 'pipeline_run_id')
    op.drop_index(op.f('ix_fallback_log_scrape_run_id'), table_name='fallback_log')
    op.drop_index(op.f('ix_fallback_log_news_run_id'), table_name='fallback_log')
    op.drop_index(op.f('ix_fallback_log_id'), table_name='fallback_log')
    op.drop_index(op.f('ix_fallback_log_fallback_type'), table_name='fallback_log')
    op.drop_index(op.f('ix_fallback_log_entity_type'), table_name='fallback_log')
    op.drop_index(op.f('ix_fallback_log_created_at'), table_name='fallback_log')
    op.drop_table('fallback_log')
    op.drop_index(op.f('ix_news_runs_status'), table_name='news_runs')
    op.drop_index(op.f('ix_news_runs_pipeline_name'), table_name='news_runs')
    op.drop_index(op.f('ix_news_runs_id'), table_name='news_runs')
    op.drop_table('news_runs')
    op.drop_index(op.f('ix_api_keys_scope'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_name'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
